language: node_js
sudo: required
node_js:
  - 12.18.0
cache:
  directories:
  - node_modules
  
branches:
  only:
    - master
  
before_install:
  - npm install hexo-cli
  
install:
  - npm install
  - npm install hexo-deployer-git -save
  
script:
  - hexo clean
  - hexo generate
  
after_script:
  - git config user.name "Winter"
  - git config user.email "zhoudong_dream@163.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./config.yml
  - hexo deploy
